name: Blade Prettier

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest
    # Check if contains [ci skip] will be skip github action
    permissions:
      # Allow ad-m/github-push-action to push commit to branch gh-pages
      contents: write
    if: (github.repository == 'OpenSID/OpenDK')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependency
        run: npm install

      - name: Pretier Blade
        run: npm run prettier-blade

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Blade Prettier Code"
